### ISSUE TITLE
Installation /Setup

### ISSUE THREAD

**Issue by MTechH7** [yuzawa-san/googolplex-theater#376]
Hi 

I am interested in this project 
However not clued up that much with linux or coding 
Would you be able to assist in a tutorial on installtion and setup?
Would be appreciated alot

Regards

**Comment by yuzawa-san** [comment]
I would advise the packagecloud installation since it is the easiest to do. https://github.com/yuzawa-san/googolplex-theater#packagecloud

**Comment by MTechH7** [comment]
I have tried this but i dont know how to setup the project at all hence why
i asked if a video tutorial would be possible

**Comment by yuzawa-san** [comment]
please be more specific. did a step fail? was there anything useful printed to the logs/shell? did you edit the configuration files (in /opt/googolplex-theater/conf)? are you on a raspberry pi? if so, what version of pi and OS? i'll need more diagnostic information and details in order to provide assistance.

if this is a systemd, linux or raspberry pi issue, these projects have a large amounts of documentation available online.

sorry, i'm not making instructional videos. if we figure out what is happening, feel free to open a PR to improve the README if you can add useful information.

**Comment by demonike84** [comment]
Hello

I am also very interested in this project but am lacking in the knowledge needed to set this up.
I would really appreciate some help.
I have installed this per the package cloud instructions but am now stuck not sure how to proceed.
Thank you in advance for any assistance

**Comment by yuzawa-san** [comment]
@demonike84 please create a new issue with details about what part you are getting stuck on? specific error messages from this project, sample output are all helpful for troubleshooting.

once again, if the issue is a general linux, command line, etc question, the internet (e.g. stackoverflow) has more on that.
